name: flutter_micro_frontend_workspace

packages:
  - apps/**
  - packages/**
  - shared/**

scripts:
  analyze:
    exec: dart analyze .
    description: Analyze the entire workspace.

  fclean:
    exec: flutter clean && flutter pub get
    description: Clean the Flutter project and get dependencies.
